brokerAddress = "LLB-Server"
clientPublishName = "PlantData"
clientSubscribeName = "PlantReader"
topic_air_temperature = "AIR_TEMP"
topic_moisture = "MOISTURE"
air_temp_pin = "0"
moisture_pin = "2"
now_string_format = "%H:%M:%S:%f"